name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - uses: actions/upload-artifact@v2
      with:
        name: NuPkg-Linux
        path: ImpromptuNinjas.UltralightSharp.*.nuget

  build-and-test-win64:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - uses: actions/upload-artifact@v2
      with:
        name: NuPkg-Win64
        path: ImpromptuNinjas.UltralightSharp.*.nuget

  build-and-test-macos:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.UltralightSharp\ImpromptuNinjas.UltralightSharp.csproj
    - uses: actions/upload-artifact@v2
      with:
        name: NuPkg-OSX
        path: ImpromptuNinjas.UltralightSharp.*.nuget